name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
